services:
  nodejs-lib:
    container_name: service_lib
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - nodejs-db
    environment:
      env_file: ".env"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:migrate:dev
    restart: always
    networks:
      - home-library

  nodejs-db:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - home-library


volumes:
  pgdata:

networks:
  home-library: